### ISSUE TITLE
ฺBUG Place-Auction

### ISSUE THREAD

**Issue by darkmagic66** [KUOnlineAuction/frontend#21]
BUG  :  สามารถ ลงสินค้าเวลาที่ผ่านมาแล้วได้  
ตัวอย่าง : ตอนนี้ 10.00 PM แต่สามารถลงสินค้าตอน 9 PM ได้
สิ่งควรจะเป็น  :  มี Response ตอบสนองว่าไม่สามารถทำได้

**Comment by pangpondwee** [comment]
ล็อคเวลาไว้แล้ว
